const contact=[
    {
        id:1,
        name:"Nature",
        info:"Peace",
        imgLk:"https://source.unsplash.com/random/?nature"
    },
    {
        id:2,
        name:"Buildings",
        info:"Cool",
        imgLk:"https://source.unsplash.com/random/?buildings"
    },
    {
        id:3,
        name:"Beach",
        info:"Wave",
        imgLk:"https://source.unsplash.com/random/?beaches"
    },
    {
        id:4,
        name:"Crypto",
        info:"Rich",
        imgLk:"https://source.unsplash.com/random/?crypto"
    },
    {
        id:5,
        name:"Rain",
        info:"Wet",
        imgLk:"https://source.unsplash.com/random/?rain"
    },
    {
        id:6,
        name:"nuclear",
        info:"Dangerous",
        imgLk:"https://source.unsplash.com/random/?nukes"
    }
];
export default contact;